name: generate github snake

on:
  schedule:
    - cron: "17 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rockabhishekak
          outputs: |
            dist/github-snake.svg?color_snake=#8b5cf6&color_dots=#172554,#1d4ed8,#4f46e5,#7c3aed,#c084fc
            dist/github-snake-dark.svg?color_snake=#67e8f9&color_dots=#0b102a,#12305f,#1f5bb5,#5b21b6,#d946ef

      - name: Publish generated SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: dist
          target_branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
